name = "RunStatistics"
uuid = "c967b8ff-7eea-41b9-8a9d-36c76a634080"
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
julia = "1"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test"]
